package com.kalsym.parentwrapper.models.enums;

public enum Status {
    BEING_DELIVERED,
    BEING_PREPAIRED,
    DELIVERED_TO_CUSTOMER,
    CANCELED_BY_CUSTOMER,
    PAYMENT_CONFIRMED,
    READY_FOR_DELIVERY,
    RECEIVED_AT_STORE,
    REFUNDED,
    REJECTED_BY_STORE,
    REQUESTING_DELIVERY_FAILED,
    AWAITING_PICKUP,
    FAILED,
    QUOTED,
}
